config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  #devise_for :members, :controllers => { :registrations => "registrations" }

  resources :projects
  resources :bugs
  resources :pages

end

app/models/project.rb
class Project < ApplicationRecord

	validates :name, presence: true
	validates :description, presence: true
	validates :user_id, presence: true

	belongs_to :user
	default_scope -> { order(updated_at: :desc)}

	has_many :bugs, dependent: :destroy
	has_many :project_users , dependent: :destroy
	has_many :users ,through: :project_users , dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	#load_and_authorize_resource
	before_action :logged_in	
	before_action :set_project, only: [:show, :edit, :update, :destroy]
	before_action :require_manager, except: [:index, :show]
	before_action :current_manger, only: [:edit, :destroy]


	def index
		if(current_user.user_type == "Manager")
	    	@user_projects = current_user.createProjects
	    else
	    	@user_projects = current_user.projects
	    end
	end

	def show
		@project_user = @project.users 
	end

	def new
		@project = Project.new
		
	end

	def create 
		@project = Project.new(project_params)
		@project.user_id = current_user.id 
		if @project.save
			flash[:success]="Project added successfully"
			redirect_to project_path(@project)
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if @project.update(project_params)
			flash[:success] = "Project updated successfully!"
			redirect_to projects_path
		else
			render 'edit'
		end
	end

	def destroy
		Project.find(params[:id]).destroy
		flash[:success] = "Project deleted successfully!"
		redirect_to projects_path
	end

	private

	def project_params
		params.require(:project).permit(:name, :user_id, :description, user_ids: [])
	end

	def set_project
		@project = Project.find(params[:id])
	end

	

	def require_manager
		if !(user_signed_in? && current_user.user_type == "Manager" )
			flash[:danger] = "Only Manager can perform this action!"
			redirect_to projects_path
		end
	end

	def current_manger
		if !(user_signed_in? && current_user.user_type == "Manager" && current_user.id == @project.user_id)
			flash[:danger] = "Only Creator Manager can perform this action!"
			redirect_to projects_path
		
		end
	end

	def logged_in
		if (!user_signed_in?)
			flash[:danger] = "You have to Log in first!"
			redirect_to '/users/sign_in'
		end

	end

end 

app/views/projects/edit.html.erb
<h1>Edit <%= @project.name %> </h1>
<hr />
<%= render 'shared/errors' , obj: @project%>
<div class="row">
	<div class="col-md-8">
		<%= form_for(@project, :html => {class: "form-horizontal", role:"form"}) do |new| %>
			<div class="form-group">
				<%= new.label :name%>
				<%= new.text_field :name , class: "form-control" ,placeholder: "Enter name of Project", autofocus: true %>
			</div>

			<div class="form-group">
				<%= new.label :description%>
				<%= new.text_area :description ,rows: 10, class: "form-control" ,placeholder: "Enter Description of Project", autofocus: true %>
			</div>
			

			<div class="form-group">	
				<%= new.label :assigned_to , "Assigned to Developer"%>		
				<%= new.collection_select :user_ids, User.where(:user_type => 'Developer'), :id, :name, {}, {:multiple => 'true'} %>
			</div>

			<div class="form-group">	
				<%= new.label :assigned_to, "Assigned to QA"%>		
				<%= new.collection_select :user_ids, User.where(:user_type => 'QA'), :id, :name, {}, {:multiple => 'true'} %>
			</div>


			<div class="form-group">
				<%= new.submit class: "btn btn-primary btn-xlarge"%>
			</div>

		<% end %>
	</div>
</div>
<hr/>

app/views/projects/index.html.erb
<h1>Project List</h1>
<hr/>
<% if user_signed_in? && current_user.user_type == "Manager"%>
	<div class="row">
		<div class="col-md-2">
			<%= link_to "Add new Project", new_project_path,class:"btn btn-primary"%>
		</div>
	</div>
<hr/>
<%end%>
<% if @user_projects.any? %>
	<% @user_projects.each do |project| %>
	<div class="row">
		<div class="well  col-md-8">
			<h4><%= link_to project.name , project_path(project) %></h4>
			<p>Description: <%= truncate(project.description, length: 50) %></p>
			<p style="font-size: 15px"><b>Assigned to: </b></p>
			<% if project.users.any?%>
				<ul>
				<% project.users.each do |user| %>
					<li> <%= user.name %> </li>
				<%end%>
				</ul>
			<%else%>
			<li>None</li>
			<% end %>
			<small>created by <b><%=  project.user.name %></b> <%= time_ago_in_words(project.created_at) %> ago</small>
		<% if user_signed_in? && current_user.user_type == "Manager"%>
			<div class="col-md-6">
				<%= link_to "Edit this Project", edit_project_path(project),class:"btn btn-primary"%>
				<%= link_to "Delete this Project", project_path(project), method: :delete, data: {confirm: "Are you sure you want to delete this Project"}, class: "btn btn-danger" %>
			</div>
		<%end%>
		</div>
	</div>
	<% end %>
<% else %>
<h4>Not have yet!</h4>
<% end %>

<hr/>

app/views/projects/new.html.erb
<%= render 'shared/errors' , obj: @project%>
<h1>Create a new Project</h1>
<div class="row">
	<div class="col-md-8">
		<%= form_for(@project, :html => {class: "form-horizontal", role:"form"}) do |new|%>
			<div class="form-group">
				<%= new.label :name%>
				<%= new.text_field :name , class: "form-control" ,placeholder: "Enter name of Project", autofocus: true %>
			</div>

			<div class="form-group">
				<%= new.label :description%>
				<%= new.text_area :description ,rows: 8, class: "form-control" ,placeholder: "Enter Description of Project", autofocus: true %>
			</div>
			

			<div class="form-group">	
				<%= new.label :assigned_to_developer, "Assigned to Developer"%>		
				<%= new.collection_select :user_ids, User.where(:user_type => 'Developer'), :id, :name, {}, {:multiple => 'true'} %>
			</div>

			<div class="form-group">	
				<%= new.label :assigned_to_qa , "Assigned to QA"%>		
				<%= new.collection_select :user_ids, User.where(:user_type => 'QA'), :id, :name, {}, {:multiple => 'true'} %>
			</div>

			<div class="form-group">
				<%= new.submit class: "btn btn-primary btn-xlarge"%>
			</div>

		<% end %>
	</div>
</div>
<hr/>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<div class="row">
	<div class="col-md-12">
		<h3> Description </h3>
		<hr/>
		<p style="font-size: 18px"><%= simple_format(@project.description) %></p>
		
		<p style="font-size: 15px"><b>Assigned to: </b></p>
		<% if @project_user.any?%>
			<ul>
			<% @project_user.each do |user| %>
				<li> <%= user.name %> </li>
			<%end%>
			</ul>
		<%else%>
			<li>None</li>
		<% end %>
		
		<small style="font-size:10px">Created by <%= @project.user.name %></small>
		<div class="pull-right">
			<small style="font-size:10px"><%= time_ago_in_words(@project.created_at)%>  ago</small>
		</div>
	</div>
</div>

<hr/>

<h4><b>Related Bugs</b></h4>
<% if(user_signed_in? && (current_user.user_type=="Manager" || current_user.user_type == "QA") ) %>
	<%= link_to "Add new bug", new_bug_path(id: @project.id),class:"btn btn-primary"%>
	<hr/>
<% end %>
<% if @project.bugs.any? %>
	<% @project.bugs.each do |bug| %>
		<div class="row">
			<div class="well  col-md-8">
				<h4><%= link_to bug.title.capitalize , bug_path(bug) %></h4>
				<p>Des: <%= truncate(bug.description, length: 50) %></p>
				<p>Type: <%= bug.bug_type %></p>
				<p>Status: <%= bug.status %></p>
				<p>Assigned to: <%= bug.developer.name %></p>
				<p>Related to: <%= bug.project.name %></p>

				<small style="font-size:10px">Created by: <%= bug.user.name %></small>
				
				<% if current_user.user_type == "Manager"%>
					<div class="col-md-6">
						<%= link_to "Edit this bug", edit_bug_path(bug),class:"btn btn-primary"%>
						<%= link_to "Delete this bug", bug_path(bug), method: :delete, data: {confirm: "Are you sure you want to delete this bug"}, class: "btn btn-danger" %>
					</div>
				<%end%>
			</div>
		</div>
	<% end %>
<% else %>
<h4 style="color: green" >No bugs yet!</h4>
<% end %>