config/routes.rb
Rails.application.routes.draw do
  
  root "projects#index"

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  
  #devise_for :members, :controllers => { :registrations => "registrations" }

  resources :projects
  resources :bugs
  resources :pages

end

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-1">
		<% flash.each do |name, msg| %>
			<div class="alert alert-<%=name%>">
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= msg %>
			</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Bugs Detecting System', projects_path , class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        
      <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name.capitalize %>'s Profie <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit you profile', '/users/edit' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>  
          <li><%= link_to 'Log in' , new_user_session_path %></li>
        <% end %>
       

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BugTrackingSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/navigation'%>
  <body>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>